pipeline {
    agent any

    stages {
        stage('Test1') {
            steps {
                echo 'Test1'
            }
        }
        stage('Test2') {
            steps {
                echo 'Test2'
            }
        }
    }
}
