pipeline {
    agent {
            label 'linux'
          }

    stages {
        stage('Setup environment') {
            steps {
                echo 'Test1'
            }
        }
        stage('Sync sources') {
            steps {
                echo 'Test2'
            }
        }
        stage('Build espressowifi') {
            steps {
                echo 'Test1'
            }
        }
        stage('Build espresso3g') {
            steps {
                echo 'Test2'
            }
        }
    }
}
