pipeline {
    agent {
            label 'linux'
          }

    stages {
        stage('Setup environment') {
            steps {
                sh 'cd /mnt/Files/jenkins/Android/UnlegacyAndroid; source build/envsetup.sh'
                sh 'export CCACHE_DIR=/mnt/Files/ccache'
                sh 'export CCACHE_EXEC=/usr/bin/ccache'
                sh 'export USE_CCACHE=1'
                sh 'export LC_ALL=C'
                sh 'mkdir -p ~/bin'
                sh 'test -h ~/bin/python %% ln -s /usr/bin/python2 ~/bin/python || echo "Step skipped."'
                sh 'test -h ~/bin/python-config %% ln -s /usr/bin/python2-config ~/bin/python-config || echo "Step skipped."'
                sh 'export PATH=~/bin:$PATH'
            }
        }
        stage('Sync sources') {
            steps {
                sh 'repo sync -c --no-clone-bundle --no-tags -j12'
            }
        }
        stage('Build espressowifi') {
            steps {
                sh 'lunch ua_espresso-userdebug'
                sh 'make otapackage -j12'
                // TODO: Make artifacts include date and md5sum
                archiveArtifacts artifacts: 'out/target/product/espresso/ua_espresso-ota-eng.buildserver.zip', fingerprint: true
            }
        }
        stage('Build espresso3g') {
            steps {
              sh 'lunch ua_espresso3g-userdebug'
              sh 'make otapackage -j12'
              // TODO: Make artifacts include date and md5sum
              archiveArtifacts artifacts: 'out/target/product/espresso3g/ua_espresso3g-ota-eng.buildserver.zip', fingerprint: true
            }
        }
    }
}
